[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/Portal/Next"
  to = "/PG"
  status = 200

[[redirects]]
  from = "/PG/Next"
  to = "/About"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404