[build]
  command = "npm run build"
  publish = "build/"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

  from = "/Portal/Next 
  to = "/PG"
  status = 200

  from = "/PG/Next 
  to = "/About"
  status = 200